name: reward
description: "A new Flutter project"
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  provider: ^6.1.1
  dio: ^5.4.0
  flutter_svg: ^2.0.10
  google_sign_in: ^6.1.6
  url_launcher: ^6.2.2
  shared_preferences: ^2.3.3
  webview_flutter: ^4.4.2
  universal_html: ^2.2.4
  flutter_secure_storage: ^9.0.0
  uni_links: ^0.5.1
  flutter_dotenv: ^5.1.0
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700
